### ISSUE TITLE
Private constructor

### ISSUE THREAD

**Issue by kdex** [tc39/proposal-class-fields#22]
Should users be allowed to declare the private field `#constructor`?

Reserving this field for future use might be appealing.

**Comment by littledan** [comment]
This is an excellent point. @erights raised this issue in the context of the [orthogonal classes proposal](https://github.com/erights/Orthogonal-Classes/blob/9cf063e0bcdfa8a3bff2c07099dbd597fade1360/README.md#the-constructor-method). In Mark's proposal, declaring a constructor method came with special abilities. We're not pursuing this proposal now, but to leave room for it, IIRC we resolved to ban public fields named `constructor` and private fields and methods named `#constructor`. Somehow, though, this didn't make it into the spec text.

Any thoughts on this prohibition? Otherwise, I'll edit the spec for this.

**Comment by erights** [comment]
Hi @kdex @littledan , yes I dropped the ball on this too. I do think we should reserve it. 

In light of this, I do notice the following unrepairable irregularity in vanilla ES6 classes:

```js
class A {
  constructor() {/*constructor body*/}
}
class B {
  ["constructor"]() {/*method body*/}
}
class C {
  "constructor"() {/*I'm not sure. What does the spec say?*/}
}
```
@allenwb @bterlson There should probably be a non-normative note somewhere pointing out this inescapable irregularity.

Fortunately this irregularity doesn't infect the private issue, since private names are not strings and cannot be computed.

**Comment by littledan** [comment]
@erights Seems like this is all based on a class element whose PropName is `"constructor"`, and PropName is based on taking the StringValue, so the third one is treated entirely as a constructor. Seems like an internally consistent story to me, at least, though another valid choice might have been to ban a method which is dynamically named `"constructor"`.

We can extend an analogous story to fields, where `constructor` and `"constructor"` are banned, but `["constructor"]` is allowed. How does that sound?

**Comment by erights** [comment]
> We can extend an analogous story to fields, where constructor and "constructor" are banned, but ["constructor"] is allowed. How does that sound?

+1

**Comment by mheiber** [comment]
part of the spec that bans `#constructor`, so we might have private constructors in future: https://tc39.github.io/proposal-class-fields/#sec-static-semantics-early-errors

**Comment by littledan** [comment]
Yes, that part of the spec was put in to address this issue.
