### ISSUE TITLE
The difference between  [[Set]] and [[Define]] 

### ISSUE THREAD

**Issue by 1316346949** [tc39/proposal-class-fields#281]
![image](https://user-images.githubusercontent.com/24400797/70958486-588c1900-20b4-11ea-83e8-8f0a36e7fed1.png)

**Comment by 1316346949** [comment]
because there are already many codes using typescript and babel defined [[set]]

**Comment by rdking** [comment]
That leaves an open problem. What does this mean?
```js
class A {
   d;  // ? Isn't defined, but theres nothing to set either!
}

**Comment by 1316346949** [comment]
> That leaves an open problem. What does this mean?
> 
> ```js
> class A {
>    d;  // ? Isn't defined, but theres nothing to set either!
> }
> ```

Setting d is undefined  or  
![image](https://user-images.githubusercontent.com/24400797/70962670-e968f180-20c0-11ea-8d27-85a2fc8219c1.png)

**Comment by nicolo-ribaudo** [comment]
> because there are already many codes using typescript and babel defined [[set]]

Babel has been using [[define]] by default since 2018 in a stable release, and for 3 years in a prerelease.

Also, TypeScript is migrating to use [[define]] by default so hopefully it will already be a solved problem when this proposal reaches stage 4.

**Comment by bigopon** [comment]
@nicolo-ribaudo Im using babel in my current company, together with TS.
I got hit by a bug when I switched to babel + typescript from TS only, which is due to this (merging projects, needed to have a unified build).

Cant say how much i want to get rid of current spec behavior, since it bloated my generated code, makes no sense for only type declaration/documentation fields, but I couldnt just switch on the loose mode. The risk of getting some incompatibility issues down the line is too much.

So for someone, if years of babel turning on that `[[define]]` semantic by default indicates anything, its just a stick, scaring them not being able do otherwise.
Im fixing a few bits and converting all exisiting/legacy code to TS, and will be so happy as I could finally safely avoid this surprising, irksome (always having to keep in the back of your mind that even with shallow hierarchy of 2 classes, it may still blow up) behavior.

**Comment by nicolo-ribaudo** [comment]
> makes no sense for only type declaration/documentation fields

I agree! That's why you can use `declare`:
```js
class A {
  declare x: string;
}
```

Btw, note that it isn't related to [[Set]] vs [[Define]]. Without `declare` and with [[Set]], that code would be transpiled to something like this:
```js
class A {
  constructor() {
    this.x = undefined;
  }
}
```

**Comment by jo32** [comment]
> > makes no sense for only type declaration/documentation fields
> 
> I agree! That's why you can use `declare`:
> 
> ```js
> class A {
>   declare x: string;
> }
> ```
> 
> Btw, note that it isn't related to [[Set]] vs [[Define]]. Without `declare` and with [[Set]], that code would be transpiled to something like this:
> 
> ```js
> class A {
>   constructor() {
>     this.x = undefined;
>   }
> }
> ```

what swift do is something like this:

```swift
class Baz: Foo {
    override var bar: Int {
        get { return 2 }
        set {
            // Whatever... 
        }
    }
}
```

The beauty of it is that it expose the risk of overriding the get set behaviors defined in parent class. Image that we have a parent class that certain attribute is designed to be immutable by defining getter and setter in this class. However, [[define]] semantic will break this if you define the same field when subclassing.

**Comment by nicolo-ribaudo** [comment]
Isn't that code equivalent the following, and not to a field?
```js
class Baz extends Foo {
    get bar() { return 2 }
    set bar(val) {
        // Whatever... 
    }
}
```

**Comment by jo32** [comment]
sorry for not adding enough introduction of Swift, in swift:

https://repl.it/@JoeJiang/swifttest
```swift
public class FooButton {
    public var weight: Double = 1.0
}

// the following works
public class BarButton: FooButton {
    override public var weight: Double {
        get {
            return 2.0
        }
        set {
            // nothing, because only red is allowed
        }
    }
}

// the following does not work
public class BazButton: FooButton {
    override public var weight: Double = 2.0
}
```

overriding getter and setter when you override a property is kind of obligatory, that's why I said it expose the risk of overriding the get set behaviors defined in parent class.
